version: '3.8'
services:
  compiler:
    container_name: compiler
    build:
      context: ./
      dockerfile: Dockerfile.compiler
    environment:
      - GOOS=${APP_OS}
      - GOARCH=${APP_ARCH}
    volumes:
      - ./:/app
    restart: always
    entrypoint: ["tail", "-f", "/dev/null"]

  debugger:
    container_name: debugger
    build:
      context: ./
      dockerfile: Dockerfile.debugger
    volumes:
      - ./:/app
    working_dir: /app
    ports:
    #   - "8080:8080"   # App Port
       - "2345:2345"   # Debug Port
    # command: ["/go/bin/dlv", "exec", "/app/appdebug", "--headless", "--listen=:2345", "--api-version=2", "--accept-multiclient", "--continue", "--log"]
    restart: always
    entrypoint: ["tail", "-f", "/dev/null"]
    
