version: '3.8'
services:
  dev:
    container_name: dev
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - GOOS=${APP_OS}
      - GOARCH=${APP_ARCH}
    volumes:
      - ./:/app
    restart: always
    entrypoint: ["tail", "-f", "/dev/null"]

    # environment:
    #   - VIEWS_DIR=/app/internal/views
    # depends_on:
    #   - db
#   db:
#     image: postgres:13
#     restart: always
#     environment:
#       POSTGRES_USER: rootusr
#       POSTGRES_PASSWORD: rootpwd
#       POSTGRES_DB: document_platform_db
#     volumes:
#       - db-data:/var/lib/postgresql/data
# volumes:
#   db-data: